version: '3.0'
services:
   db:
     image: hypriot/rpi-mysql
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: aspnetcoreappskeleton
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: T72a6oYb^o4IAY8
     volumes:
       - dbdata:/var/lib/mysql
       - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
     restart: always
   aspnetcoreappskeleton:
     depends_on:
       - db
     image: kryptoncontainer/aspnetcore31appskeleton
     ports:
       - "8088:80"
volumes:
    dbdata: