version: '3.0'
services:
   db:
     image: hypriot/rpi-mysql
     environment:
       MYSQL_RANDOM_ROOT_PASSWORD: 1
       MYSQL_DATABASE: db1
       MYSQL_USER: dbuser
       MYSQL_PASSWORD: secret
     volumes:
       - dbdata:/var/lib/mysql
     restart: always
     container_name: mysqldb
   aspnetcoreappskeleton:
     depends_on:
       - db
     image: kryptoncontainer/aspnetcore31appskeleton
     ports:
       - "8088:80"
     container_name: app
     restart: always
volumes:
    dbdata: