// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Programatica.AspNetCore31AppSkeleton.Data.Migrations.Context;

namespace Programatica.AspNetCore31AppSkeleton.Data.Migrations.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Programatica.AspNetCore31AppSkeleton.Data.Models.Dummy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDestroyedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Dummies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(9175),
                            CreatedUser = "system",
                            Description = "Dummy One",
                            IsDestroyed = false,
                            IsSystem = false,
                            SystemId = new Guid("9b1d2103-15a5-439d-9951-7b535503033a")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(9279),
                            CreatedUser = "system",
                            Description = "Dummy Two",
                            IsDestroyed = false,
                            IsSystem = false,
                            SystemId = new Guid("fab62bdf-b7f6-445e-b594-880dd21bd7ae")
                        });
                });

            modelBuilder.Entity("Programatica.AspNetCore31AppSkeleton.Data.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDestroyedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(452),
                            CreatedUser = "system",
                            IsDestroyed = false,
                            IsSystem = true,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(513),
                            LastModifiedUser = "system",
                            Name = "Administrators",
                            SystemId = new Guid("e67e981a-1a4a-4f74-b2b7-37cf1435903c")
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(609),
                            CreatedUser = "system",
                            IsDestroyed = false,
                            IsSystem = true,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(613),
                            LastModifiedUser = "system",
                            Name = "Users",
                            SystemId = new Guid("58cf4e21-bfb2-4c11-b4b6-2246a2579bda")
                        });
                });

            modelBuilder.Entity("Programatica.AspNetCore31AppSkeleton.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDestroyedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 62, DateTimeKind.Utc).AddTicks(3901),
                            CreatedUser = "system",
                            Email = "admin@server.com",
                            Fullname = "System Administrator",
                            IsDestroyed = false,
                            IsSystem = true,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 62, DateTimeKind.Utc).AddTicks(6888),
                            LastModifiedUser = "system",
                            Password = "pass",
                            SystemId = new Guid("33c46243-cef2-4126-9364-bce89f5ad46e"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 63, DateTimeKind.Utc).AddTicks(549),
                            CreatedUser = "system",
                            Email = "user@server.com",
                            Fullname = "Just an User",
                            IsDestroyed = false,
                            IsSystem = false,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 63, DateTimeKind.Utc).AddTicks(566),
                            LastModifiedUser = "system",
                            Password = "pass",
                            SystemId = new Guid("eb1cf9fe-7a11-4c3b-bcf3-aea230055f34"),
                            Username = "user"
                        });
                });

            modelBuilder.Entity("Programatica.AspNetCore31AppSkeleton.Data.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDestroyedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(5518),
                            CreatedUser = "system",
                            IsDestroyed = false,
                            IsSystem = true,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(5539),
                            LastModifiedUser = "system",
                            RoleId = 1,
                            SystemId = new Guid("bb5ff4c3-de6d-405d-9edb-b54f08b66664"),
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(5676),
                            CreatedUser = "system",
                            IsDestroyed = false,
                            IsSystem = true,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(5680),
                            LastModifiedUser = "system",
                            RoleId = 2,
                            SystemId = new Guid("73d85165-c40f-4a49-b874-47723e36c9d1"),
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(5732),
                            CreatedUser = "system",
                            IsDestroyed = false,
                            IsSystem = true,
                            LastModifiedDate = new DateTime(2020, 10, 23, 18, 52, 22, 67, DateTimeKind.Utc).AddTicks(5737),
                            LastModifiedUser = "system",
                            RoleId = 2,
                            SystemId = new Guid("744862fc-3d59-4e87-99e2-33494fb21c16"),
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Programatica.Framework.Data.Models.Audit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentFunction")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<Guid>("ContentSystemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDestroyedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("Audit");
                });

            modelBuilder.Entity("Programatica.Framework.Data.Models.TrackChange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuditId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastDestroyedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastDestroyedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastModifiedUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SystemId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AuditId");

                    b.ToTable("TrackChanges");
                });

            modelBuilder.Entity("Programatica.AspNetCore31AppSkeleton.Data.Models.UserRole", b =>
                {
                    b.HasOne("Programatica.AspNetCore31AppSkeleton.Data.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Programatica.AspNetCore31AppSkeleton.Data.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Programatica.Framework.Data.Models.TrackChange", b =>
                {
                    b.HasOne("Programatica.Framework.Data.Models.Audit", "Audit")
                        .WithMany()
                        .HasForeignKey("AuditId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
